M48
; DRILL file {KiCad 9.0.5} date 2025-12-23T11:29:24-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-23T11:29:24-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X64.77Y-34.798
X64.77Y-117.475
X67.31Y-34.798
X67.31Y-117.475
M30
